import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Just_Another_Hand } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-roboto",
});

const justAnotherHand = Just_Another_Hand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-handwriting",
});

export const metadata: Metadata = {
  title: "Nicolette Pascual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${roboto.variable} ${justAnotherHand.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
